### ISSUE TITLE
More control of the cipher suites used

### ISSUE THREAD

**Issue by Archcry** [jwilder/nginx-proxy#1108]
Currently you can only use one of the presets, it would be nice to create your own custom cipher suite and define your own tls version (especially with TLS1.3 being available now).

I suggest adding two new environment variables for this:
`SSL_CIPHER_SUITE` in which you specify the Cipher Suite
`SSL_PROTOCOL` in which you specify your SSL protocol (defaults to TLS 1.0, 1.1 and 1.2, like mozilla intermediate)

Only when `SSL_CIPHER_SUITE` is specified we override the `SSL_POLICY` environment variable, because the `SSL_PROTOCOL` has a default we don't have to specify this one explicitly (and the ssl_protocol specified by `SSL_POLICY` is used when `SSL_CIPHER_SUITE` is not set). When nothing is specified be just fall back to the default Mozilla intermediate policy.

I might be able to make a pul-request about this, just tell me what you think of the idea.

**Comment by Archcry** [comment]
Just giving a casual bump, @kamermans could you look into my suggestion :)

**Comment by kamermans** [comment]
Hi @Archcry, thanks for the bump!  I did actually [suggest this as a possibility](https://github.com/jwilder/nginx-proxy/pull/957#issuecomment-342336668) when we implemented it last year, but we (@buchdag and @jwilder) agreed to use the more simplistic `SSL_POLICY` instead.  One of the main reasons I suggested avoiding a custom protocol/cipher suite is that the HSTS policy, DHParam length, OCSP Stapling, and possibly other features are also sort-of dependent on the policy you choose, so the user would need to get all of those settings right in order to have consistent SSL/TLS policy.  I would recommend you read through that thread to see how we came about the decision.  My general feeling is that we should continue to update the policies that we have explicit support for (the [Mozilla TLS Policies](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility), for example.  @jwilder said something similar in the original thread back in November/December.

I think we should definitely add TLS 1.3 to the list of supported protocols for all the policies since they all should support the latest version of TLS.

**Comment by Archcry** [comment]
Pull-request is merged now, please note that the alpine version of the nginx container is not up-to-date to support TLSv1.3 because alpine hasn't updated to a newer version (`>1.1.1`) of `openssl` yet.

**Comment by Abdedine** [comment]
Hi

I've declared in my docker-compose those env. variables but TLS 1.0 is still enabled :(

SSL_CIPHER_SUITE: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256

SSL_PROTOCOL: TLSv1.2 TLSv1.3

Any idea please ?

**Comment by verglor** [comment]
Hi, `nginx:1.15.8-alpine` is now built with OpenSSL `1.1.1a` so we can proceed towards TLS 1.3 !

**Comment by Archcry** [comment]
Closing this issue because TLS1.3 is not working with this container.

**Comment by DatAres37** [comment]
So there's no possibility to modify the SSL ciphers and TLS versions?
I'd just like to point out that SSLlabs will decrease the score to a B if TLS 1.0 and 1.1 are still active in January.
