### ISSUE TITLE
Deny specific IP for specific VIRTUAL_HOST

### ISSUE THREAD

**Issue by Loxeno** [jwilder/nginx-proxy#1274]
Hi,

I would like to know if there is any elegant way to deny IP for a specific VIRTUAL_HOST.
Can't find anything in the Wiki nor in issues that feet my needs.

I just want to add a conf file under conf.d with instruction for my domains.
These instructions can be based on specific locations for specific VIRTUAL_HOST or the whole VIRTUAL_HOST.

Any idea ?
A feature like this #859 could be nice. 

P.S.
I don't use any Shipyard or Portainer.
Just want to keep it KISS.

By advance, thank you.

**Comment by Greek64** [comment]
Assuming `example.com` is your VIRTUAL_HOST, the contents of file `vhost.d/example.com` are added into the `server {}` block of the nginx conf for this host, and the the contents of file `vhost.d/example.com_location` are added into the default `location / {}` block of the very same `server {}` block for this host.

So in essence this issue breaks down into more of a general nginx configuration question rather than a `nginx-proxy` one.  

Now, my nginx-foo is not the best, but what you are asking is simply a file `vhost.d/example.com_location` with following contents:
```
deny IP;
```
and that's it.  This will deny all access to this IP on this VIRTUAL_HOST.
I would suggest reading some tutorials/docs like [this](https://www.cyberciti.biz/faq/linux-unix-nginx-access-control-howto/) for more complex settings.

If you want a more fine tuned access denying, add location blocks inside the `vhost.d/example.com` file.  
The `nginx.tmpl` file of this repo gives you an idea how the configuration of the nginx is generated with all this files (i.e. position, default values, ...)

**Comment by Loxeno** [comment]
So I missed it in the documentation.

I just tested it with a whole domain, worked like a charm.

Thank you
