### ISSUE TITLE
Real remote IP adress

### ISSUE THREAD

**Issue by tdemalliard** [jwilder/nginx-proxy#130]
Hello,
I would like to share an issue I got today and its solution. Maybe this could be a note in the readme file.

I am running a nginx server behind this nginx proxy. It works great until I wanted to set up a filter by IP rule. **The client IP address passed to my nginx server was the proxy one** :(
Solution: I added this code into my server section.
```
    real_ip_header X-Forwarded-For;
    set_real_ip_from 0.0.0.0/0;
```
Now, I got the right IP.

Thank you for this nice container.

**Comment by finferflu** [comment]
I think it'd be useful to have this as the default configuration. For the time being I've decided to spin my own image (finferflu/nginx-proxy:real-ip) as indicated in this image's documentation.

**Comment by movingfox** [comment]
@tdemalliard could you describe your method in more details ? I encounter the same problem recently, and it seems that I miss something to follow your steps.

Strange, I remember the logs used to show the real client IPs days ago.

**Comment by md5** [comment]
This could definitely be documented better, but here's the relevant portion of `nginx-proxy`'s config file: https://github.com/jwilder/nginx-proxy/blob/4a99ac554824cde8be34cc173abc7cf1ef69dd7a/nginx.tmpl#L30-L31

There are two headers being set/modified by `nginx-proxy`:

* `X-Real-IP`: set to `$remote_addr`, which is the IP address seen by the Nginx process in the container. In the typical case with a `-p 80:80`, this will be the IP address that is connecting to the Docker host (either the HTTP client itself, a load balancer, a proxy, a NAT gateway, etc).
* `X-Forwarded-For`: set to `$proxy_add_x_forwarded_for`

Here's the description of `$proxy_add_x_forwarded_for` from the Nginx docs:

> the “`X-Forwarded-For`” client request header field with the `$remote_addr` variable appended to it, separated by a comma. If the “`X-Forwarded-For`” field is not present in the client request header, the `$proxy_add_x_forwarded_for` variable is equal to the `$remote_addr` variable

In @tdemalliard's case, the backing container is Nginx, so the `real_ip_header X-Forwarded-For` tells Nginx to use the `X-Forwarded-For` coming from `nginx-proxy` to determine the actual client IP address. The `set_real_ip_from 0.0.0.0/0` setting tells Nginx to trust the `X-Forwarded-For` header from any client, which is a not a secure setup. It would be better to use the actual CIDR range of the Docker bridge that connects `nginx-proxy` to its backends, but doing this automatically could be tricky since it's possible, though uncommon, for the bridge network range to vary by installation (it's usually 172.17.0.0/16).

If your backing container is running something other than Nginx, then you'll need to figure out how to use the `X-Real-IP` and/or `X-Forwarded-For` headers to get the right IP address for use in your configuration.

**Comment by finferflu** [comment]
@md5 What if nginx-proxy sees the remote address as the one assigned to the Docker interface? I'm having this issue and no matter what's running behind Nginx, I can't get nginx-proxy to see the actual original IP to start with…

@movingfox Could what I described be your issue as well?

**Comment by md5** [comment]
I'm not sure what you mean by "the Docker interface". Do you mean you're seeing the IP address of the `docker0` bridge as the incoming IP address to `nginx-proxy`?

In the case of port forwarding, `iptables` is forwarding the packet from the Docker host's external interface (from whichever IP address received the request) to port 80 (or 443) on the `nginx-proxy`'s IP address. Since `iptables` doesn't touch the IP address in this case, you shouldn't see an address on the `docker0` bridge at all.

In my case (boot2docker), I generally hit `nginx-proxy` by browsing to 192.168.59.103. When I do that, my `nginx-proxy` logs show me connecting from 192.168.59.3. This is the IP address that will end up in `X-Real-IP` and appended to `X-Forwarded-For`.

@finferflu Could you describe more about your Docker host's networking setup and how your HTTP client connects to it?

**Comment by finferflu** [comment]
@md5 You're correct, I'm only seeing `docker0`'s IP (172.17.42.1). I didn't really want to plug my issue into this topic, but I've described more in detail what's happening in [a separate issue](https://github.com/jwilder/nginx-proxy/issues/133), and I thought my input here might help as well. I guess I might add that in my setup the Docker daemon is started with `DOCKER_OPTS="—iptables=false"`.

**Comment by md5** [comment]
I don't think `--iptables=false` will help you. Happy to discuss your issue on #133.

**Comment by tdemalliard** [comment]
@md5 I agree that the setting ``set_real_ip_from 0.0.0.0/0;`` is not the max securirty. I am changing it to ``set_real_ip_from 172.17.0.0/16;``. 

I believe that as I am launching my backing container without any published port, the container cannot be reached from outside the host and it is enough security. Am I to naive?

@movingfox md5 described it well. Here is exactly what I am doing:
```bash
# all run with a centos 7 server
# launch nginx-proxy
docker run -d -p 80:80 --security-opt=label:type:docker_t --name nginx-proxy -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy
 
# launch by web application container.
# I changed some information by 'example'
docker run -d -e VIRTUAL_HOST=example.com -h example.com -v /data/example:/srv --name example tdemalliard/example
```
And the beginning of my nginx.conf file in my example container:
```yaml
user www-data;
worker_processes  1;
daemon off;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;


    server {
        server_name sdas.cartagene.qc.ca;       ## <-- Your domain.
        root /srv/sdas;  ## <-- Path to your Drupal files.

        # issue with ip and the nginx proxy
        real_ip_header X-Forwarded-For;
        set_real_ip_from 172.17.0.0/16;
```

**Comment by wandebandera** [comment]
https://github.com/jwilder/nginx-proxy/issues/133#issuecomment-456764274

**Comment by torarnv** [comment]
From what I can tell, using `set_real_ip_from 172.17.0.0/16;` isn't any more secure than `set_real_ip_from 0.0.0.0/0;`, since all the incoming traffic to the container will come from the same IP in the docker bridge. In both configurations you're basically trusting the client to not spoof the `X-Forwarded-For` header.

**Comment by torarnv** [comment]
```cfg
# Note: Since we're never seeing the real IP of the CF servers
# we have to trust the Docker bridge network, which effectively
# means we're trusting every client connecting to our server.
# The security of this setup relies entirely on all connections
# to our server coming in via CF, not directly to the origin.
# This is ensured via IP whitelisting and authenticated pulls.
real_ip_header CF-Connecting-IP;
set_real_ip_from 172.16.0.0/12;
```
