### ISSUE TITLE
/etc/nginx/conf.d/default.conf read only

### ISSUE THREAD

**Issue by kcindric** [jwilder/nginx-proxy#1371]
Is there a way I could persist the changes I mage in the nginx configuration file? I made a volume for it and I need to add a few lines for my services to work but everytime I restart nginx the default.conf gets overwritten.

I tried forcing it as read-only in the volume configuration but then nginx-proxy refuses to build.

Thanks!

**Comment by olexs** [comment]
If you need to add extra configuration, do so with an additional file under` /etc/nginx/conf.d/<whatever>.conf` (or under `/etc/nginx/vhost.d/<vhost>`). For example, I have several domain 301 redirects configured via files in the global `conf.d` folder, and an increased uploaded file size limit for a single virtual host in `vhost.d`.

The `default.conf` is read-only, because it's autogenerated from all detected virtual hosts and abovementioned custom configuration files. It can be overwritten at any time, you should not be making changes manually in there.

**Comment by kcindric** [comment]
Thanks for the info, this helped!
