### ISSUE TITLE
Weird problem - no upstream

### ISSUE THREAD

**Issue by rivaros** [jwilder/nginx-proxy#229]
I am running nginx-proxy the following way
```
docker run -d --name vhost-proxy -p  80:80 -p  443:443 -v /var/run/docker.sock:/tmp/docker.sock:ro \
-v /ssl_certs:/etc/nginx/certs \
jwilder/nginx-proxy > /dev/null
```

After this I experience problem with proxing to container. When I log in to vhost-proxy conainer
and cat /etc/nginx/conf.d/default.conf I get this:
```
server {
        server_name v3.myhost.lan;
        listen 80 ;
        return 301 https://$host$request_uri;
}

server {
        server_name v3.myhost.lan;
        listen 443 ssl spdy ;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;

        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;

        ssl_certificate /etc/nginx/certs/v3.myhost.lan.crt;
        ssl_certificate_key /etc/nginx/certs/v3.myhost.lan.key;



        add_header Strict-Transport-Security "max-age=31536000";



        location / {
                proxy_pass https://v3.myhost.lan;

        }
}
```
The upstream part is completely missing, so v3.myhost.lan cannot be reached (I get 502 Bad Gateway from nginx-proxy).

**Comment by rivaros** [comment]
Found the issue - I needed to set VIRTUAL_PORT=443 in my docker container.
Pls make this requirement more obvious in docs. Especially when you use try to proxy to 443, you het these problems.

**Comment by md5** [comment]
@rivaros Are you sure you have the current version of the image?

In the scenario you describe, you should always get an `upstream` block. If your backend container exposes only port 443, it should work. If it exposes more than one port and none of them are port 80, you should see `server {{ .Container.IP }} down;` and get a 502 error. Otherwise, you should see it try to connect to port 80.

Also, be aware that `VIRTUAL_PROTO=https` will be needed if you're connecting to an HTTPS backend.

All of this seems sufficiently documented to me in the "Multiple Ports" and "SSL Backends" sections of the `README.md`, but feel free to offer some concrete suggestions of how you thing the docs could be improved (or better yet, create a PR for discussion).

**Comment by rivaros** [comment]
@md5, Thank you for the answer. VIRTUAL_PROTO=https was set. Yes, my container had multiple ports exposed (443,3306), but not 80. And what was needed was VIRTUAL_PORT=443.
Really the upstream block existsed, but docker-gen inserted so many spaces into nginx.tmpl, so when I did docker exec vhost-proxy cat /etc/nginx/conf.d/default.conf, it was simply somewhere lost far in the top, stupid of me not to notice it immediately.

**Comment by md5** [comment]
Actually, I spoke too soon. The `docker-gen` changes to omit blank lines by default are in an unmerged PR: https://github.com/jwilder/docker-gen/pull/104
