### ISSUE TITLE
Don't expose the Docker socket (not even to a container)

### ISSUE THREAD

**Issue by grahovam** [jwilder/nginx-proxy#242]
Have you read the following news already?

https://www.lvh.io/posts/dont-expose-the-docker-socket-not-even-to-a-container.html

Is using this docker image a security risk?

**Comment by thomasleveil** [comment]
the documentation says to mount the socket in read-only mode `-v /var/run/docker.sock:/tmp/docker.sock:ro`, so one could not exploit it to control the docker daemon

**Comment by wader** [comment]
But readonly is only to not be able to remove the socket file right?

So to be able to write to it guess a container would need to inject something thru environment variables read by nginx-proxy that somehow would cause it to write to the socket? e.g. bug in dockergen, go template injection/bug or nginx config parser bug?

**Comment by md5** [comment]
Since the socket is already being used to do bidirectional HTTP communication with the deamon, all the threats listed in that article apply to `jwilder/nginx-proxy`. However, the exploit would have to be a network accessible exploit in Nginx in order to gain access to the socket.

If you're particularly concerned about this threat in terms of using the `nginx-proxy` image, then you can run a separate `docker-gen` container that is not exposed to the network as described in the docs.

I think that article is good for highlighting the issue in general, but it seems to be less of an issue with regard to this image. Of course, if someone were to put a backdoor into this image, then you'd be in trouble. If you're concerned about that, you'll need to build and host your own private copy of this image after vetting it.

**Comment by jwilder** [comment]
@md5 summed it well.
