### ISSUE TITLE
mapping 2 ports 

### ISSUE THREAD

**Issue by go-ethergit** [jwilder/nginx-proxy#247]
Hey @jwilder Jason, 

Thanks really helpful tool, 
is there easy way to use it 
to config routing to 2 different
ports on the  same DNS ?

Thanks in advance
Roman

**Comment by jwilder** [comment]
Not sure I understand I fully understand what you want to do.  Do you want something like `example.com` to route to two different containers running on different ports?  You should be able do that by starting each container with the same `VIRTUAL_HOST` value and specifying a `VIRTUAL_PORT` for each.  The proxy will just round-robin load balance them.

**Comment by jmatsushita** [comment]
Hi, not sure if this was the intent of the OP but in my case I'd be interested in using the nginx-proxy name based virtual hosting together with several upstream ports exposed by the proxy (to put [this setup](https://github.com/Nuance-Mobility/Hera-Monitoring) behind nginx-proxy).

This would mean the following
 - example.org -> container:80
 - example.org:4242 -> container:4242
 - example.org:8080 -> container:8080

I guess that a syntax for VIRTUAL_POST such as : ```-e VIRTUAL_PORT="80:80,4242:4242,8080:8080"``` might do the job and keep backwards compatibility while reusing an idiom from docker.

PS: I'm aiming at modifying the Hera-Monitoring nginx setup to serve the main site from 80 instead of 443, but to reuse the setup as is I guess it would require to allow nginx-proxy to also trust the [self-signed certificate](https://github.com/Nuance-Mobility/Hera-Monitoring/blob/master/run/nginx/config/nginx.conf#L24) which I guess is another possible feature.

**Comment by ollin** [comment]
+1 allow more then one port exposed

**Comment by byrnedo** [comment]
maybe look at https://github.com/jwilder/nginx-proxy/issues/59
there's a link to a fork in there.
