### ISSUE TITLE
can you add Let's Encrypt

### ISSUE THREAD

**Issue by AdminJack** [jwilder/nginx-proxy#274]
Our project is very nice.
It is possible to add the Let's Encrypt Script to get free and automated SSL-certificates for each container?
Look here: https://github.com/letsencrypt/letsencrypt/tree/master/letsencrypt-nginx

That can be the whipped cream. ;)
P.S. Let's Encrypt should be availability for production in  week of November 16, 2015
https://letsencrypt.org/2015/08/07/updated-lets-encrypt-launch-schedule.html

**Comment by AdminJack** [comment]
I found the solution: https://letsencrypt.readthedocs.org/en/latest/using.html#running-with-docker

**Comment by captncraig** [comment]
"production working" does not mean generally available. They won't issue certs until at least Nov 16. I wouldn't be surprised if that schedule slips yet again.

**Comment by md5** [comment]
@AdminJack It's not going to be possible to run those instructions in a straightforward way with this image. Those instructions involve running a Docker image called `quay.io/letsencrypt/letsencrypt`. That image appears to start its own Python-based web application that listens on port 443 and port 80, which would conflict with the Nginx daemon running in the `nginx-proxy` image.

In order to do what you suggest, this image would somehow have to run the `letsencrypt` app while waiting to verify control of the domain and getting the certificate, then switch over to running Nginx for `nginx-proxy` purposes. It would also presumably have to do this any time a new virtual host is detected.

There's also the fact that once this certificate was retrieved and installed, it would have to be stored in a volume to avoid being lost when the `nginx-proxy` Docker container is replaced (say to pull in an updated version of the `nginx-proxy` image).

It's also going to be problematic to run `quay.io/letsencrypt/letsencrypt` on the same host as `nginx-proxy` at the same time, since they both need to be exposed on port 443. As far as I could see, there isn't a way to run the `quay.io/letsencrypt/letsencrypt` Docker image on an alternate port.

**Comment by md5** [comment]
All that being said, there *may* actually be some way to run `quay.io/letsencrypt/letsencrypt` *behind* `nginx-proxy` with `VIRTUAL_HOST` set that could actually work. I'm not sure what `quay.io/letsencrypt/letsencrypt` is doing and how the validation client is connecting back to it to know for sure.

**Comment by dropfen** [comment]
letsencrypt (not the docker image) will put the files here:

```
/etc/letsencrypt/live/my.domain.com/
--> cert.pem
--> privkey.pem
--> chain.pem
--> fullchain.pem
```
so, if I create a dir 
```
/etc/proxy-ssl
--> my.domain.com.crt --> /etc/letsencrypt/lime/my.domain.com/cert.pem
--> my.domain.com.key --> /etc/letsencrypt/lime/my.domain.com/privkey.pem
```
and run my container with `-v /etc/proxy-ssl:/etc/nginx/certs`  it should work, right?

Have I missed something?

**Comment by md5** [comment]
@dropfen That won't work unless you also mount `/etc/letsencrypt/mydomain.com` into the container since those symlinks will be dangling otherwise.

**Comment by dropfen** [comment]
@md5 right. So we actually know the naming convention of letsencrypt. The best scenario would be to mount it as /etc/nginx/certs and use their naming conventions their

**Comment by dropfen** [comment]
Which language is the nginx.tmpl file written?

**Comment by md5** [comment]
It use Go's text.template package. There are additional custom functions
added in the docker-gen command.

**Comment by julien-hadleyjack** [comment]
Using the ports 80 or 443 is one way to authenticate to the let's encrypt service. [The documentation](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins) lists other possibilities besides `standalone`.

I managed to get it working with the `webroot` option. It creates a folder called `.well-known` under your web root. You can use the Per-VIRTUAL_HOST configuration to point it to a volume.

Another option that might work better in the long term is the `nginx` option. But I haven't looked into it yet because it is marked experimental.

**Comment by dmp1ce** [comment]
I'm interested in this too. Ideally, nginx-proxy could validate new certificates without affecting the backend.

**Comment by fuerst** [comment]
If shutting down nginx-proxy while the certificate is generated is an option you may use the following commands. Assuming that:

1. The nginx-proxy docker container is called _nginx-proxy_.
2. The certificate files for nginx-proxy are locate at _/root/nginx-proxy-certs/_.
3. The domain is called _domain.tld_

```
docker stop nginx-proxy
./letsencrypt  --agree-tos --agree-dev-preview certonly -d domain.tld
cp /etc/letsencrypt/live/domain.tld/privkey.pem /root/nginx-proxy-certs/domain.tld.key
cp /etc/letsencrypt/live/domain.tld/fullchain.pem /root/nginx-proxy-certs/domain.tld.crt
docker start nginx-proxy
```

**Comment by dmp1ce** [comment]
I created a fork with Let's Encrypt support. See the pull request. #300.

I used the [simp_le](https://github.com/kuba/simp_le) Let's Encrypt client and a bash script.

**Comment by PierreZ** [comment]
I made a [fork](https://github.com/PierreZ/nginx-proxy) of nginx-proxy for out of the box support of Let's Encrypt. Not ready to go upstream but it's a start

**Comment by fbender** [comment]
You might want to have a look at [mbrugger/letsencrypt-nginx-docker](https://github.com/mbrugger/letsencrypt-nginx-docker) – this is a prime candidate for integration with `nginx-proxy`.

**Comment by PierreZ** [comment]
Thanks for your liink! Unfortunatly, this nginx is not fully automated. In my case, I don't have a cron and everything needs to be working. Don't get me wrong, my solution is working, but it's not really clean. I posted here if someone is looking for a kickstart to do a better code than mine ;)

**Comment by JrCs** [comment]
I have a solution with the original letsencrypt client integrated in nginx-proxy. I need some time to stabilize it...

**Comment by Finkes** [comment]
@dropfen did you manage to get letsencrypt to work with this proxy? My browser does not trust the certs.

**Comment by dropfen** [comment]
@Finkes sorry, I can't tell you, because I did't tried it yet

**Comment by ambroisemaupate** [comment]
Here is my script to run nginx-proxy with letsencrypt certs:

```bash
#!/bin/bash
#

docker run  -d -p 80:80 -p 443:443 \
            --name="front-proxy" \
            -v /var/run/docker.sock:/tmp/docker.sock \
            -v /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro\
            -v /etc/letsencrypt/live:/etc/letsencrypt/live:ro \
            -v /root/front-proxy/certs:/etc/nginx/certs:ro \
            -v /root/front-proxy/vhost.d:/etc/nginx/vhost.d:ro \
            -v /root/front-proxy/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro \
            --restart="always" \
            jwilder/nginx-proxy
```

Then I make symlinks in `/root/front-proxy/certs` from `/etc/letsencrypt/live/my.domain.com/fullchain.pem` and `privkey.key`

You have to make volumes for `/etc/letsencrypt/live` and `/etc/letsencrypt/archive` if you want your symlinks to work through your container to your host.

**Comment by hrwebasst** [comment]
It's actually quite a bit easier than that ^^ I made a blog post about it if anyone cares to look here [zettabyte.me](https://zettabyte.me/lets-encrypt-with-docker-nginx-proxy/)

It's as easy as making a couple of symlinks:
```bash
sudo ln -s /etc/letsencrypt/live/example.com/privkey.pem /var/local/proxy-certs/example.com.key
sudo ln -s /etc/letsencrypt/live/example.com/cert.pem /var/local/proxy-certs/example.com.crt
```
Then running the following to start the proxy:
```bash
docker run -d -p 80:80 -p 443:443 --name=proxy --restart=always \
 -v /var/local/nginx/certs:/etc/nginx/certs -v /etc/letsencrypt:/etc/letsencrypt \
 -v /var/local/proxy-confs:/etc/nginx/vhost.d:ro \
 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

**Comment by JrCs** [comment]
@ambroisemaupate and @hrwebasst you are offtopic.
This issue is about integrated letsencrypt directly info the ngnix-proxy container to create and renew certs automatically.

**Comment by md5** [comment]
@JrCs I don't think those comments are off-topic. This issue should be the place to discuss whether Let's Encrypt support should be built-in or whether it should be done through coordinating with other containers (and if so, what level of accomodation should be added to make it easy for other containers to add this support).

**Comment by philkunz** [comment]
I thought a little about it, and I believe the best approach would be to have a separate docker container (**letsencrypt-nginxproxy**) that exposes one port for domain validation and another one for obtaining the certificates (to store them inside **nginx-proxy**).

Since **nginx-proxy** already listens to new containers being started, the **letsencrypt-nginxproxy** container could have a special env variable that tells **nginx-proxy** that it is time to pull in the new certificates when started.  **letsencrypt-nginxproxy** should terminate once done.

**letsencrypt-nginxproxy** should look for VIRTUAL_HOST envs just like **nginx-proxy** and request certificates for all given domains.

**Comment by PierreZ** [comment]
I don't see why we need to divide into smaller containers. LE is in beta for now, but they will be "production ready" some day, and at that time, registration will be easier I think (no google form). That means that Traefik could generate dynamically generate a new cert for each new frontend.

nginx-proxy is only working with Docker for example. If we need to make a LE generator, we need to find a way to trigger the execution. I'm currently using a fork version of nginx-proxy with Let's Encrypt, here's what I do:

- Start LE official container and expose volume /etc/letsencrypt
- Use --volumes-from option on my fork of nginx-proxy

It's not dynamic (e.g I need to restart my containers to generate a new certs), and I was hoping replace nginx-proxy with Traefik with Let's Encrypt support in a easy mode. Something like:

- Declare "letsencrypt = true" on config file
- That's it! It will generate on the fly certificates

**Comment by JrCs** [comment]
I'm currently working on a separate container that will automatically create/renew certs and that use the original nginx-proxy for challenges validation.

**Comment by jacobtomlinson** [comment]
I've done a bit of thinking about this and feel there needs to be a no downtime solution.

At home I've got a cron job which stops nginx, runs lets encrypt to generate certs and then starts nginx again. This results in a few seconds of downtime, which is fine for my home server.

However in a production environment those seconds of downtime would be best avoided. Therefore it may be better to use the webroot authentication method instead of the standalone. Webroot adds a file to a location accessible on your server to authenticate against, while leaving your server running, and then removes it again.

I wonder if it would be possible to have a lets encrypt container running a simple web server which implements the webroot method. Then have the proxy detect that this container is running and proxy just that file location to the lets encrypt container while leaving the rest of the proxy pointing at the service.

Then when the lets encrypt container exits remove that single file proxy.

**Comment by JrCs** [comment]
@jacobtomlinson my [letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) container allow to create/renew Let's Encrypt certificates with no downtime at all.

**Comment by jacobtomlinson** [comment]
@JrCs Neat! What authentication method does it use to get no downtime?

**Comment by JrCs** [comment]
@jacobtomlinson It use webroot with nginx-proxy has webserver

**Comment by jacobtomlinson** [comment]
@JrCs Perfect! That's pretty much what I was going to make, you've saved me a lot of time there, thanks!

**Comment by JulianKingman** [comment]
Awesome @JrCs, I'll have to set that up before my certs expire :)
and thanks @hrwebasst for the clear explanation of how-to

**Comment by SteveLTN** [comment]
I made an image that obtains certificates from Let's Encrypt, and it uses docker-gen to do container discovery in a similar way as Nginx-proxy. 

https://github.com/SteveLTN/https-portal

**Comment by sopitz** [comment]
We have integrated letsencrypt with nginx-proxy. It's a new image that has jwilder/nginx-proxy:0.2.0 as base image. It will auto generate ssl certs for all vhosts. Only when you create the container for the first time, it might take up to 10 minutes before the ssl cert actually shows up. That's due to the update process letsencrypt runs at startup. Have a look here and let me know what we can do! We are happy to make it better for all!

https://hub.docker.com/r/eforce21/letsencrypt-nginx-proxy/
https://github.com/eforce21/letsencrypt-nginx-proxy

**Comment by almereyda** [comment]
I have turned the setup from @JrCs into a small, opinionated [`docker-compose`](https://github.com/jwilder/docker-gen/issues/77) example at [docker-nginx-gen-letsencrypt](https://github.com/ecobytes/docker-nginx-gen-letsencrypt).

**Comment by gw0** [comment]
There is also an alternative implementation: https://github.com/tozd/docker-nginx-proxy

**Comment by almereyda** [comment]
And another https://github.com/sashee/letsencrypt-proxy-docker

**Comment by pierreozoux** [comment]
And another: https://github.com/indiehosters/nginx (forked from @almereyda )

Yes @almereyda you can now choose between haproxy and nginx with LibrePaaS \o/ :)

@jwilder I really think it would be nice this repo gives a basic docker-compose file with letsencrypt capabilities.

**Comment by mareeba** [comment]
I can confirm that @SteveLTN 's solution mentioned above works really well and allows containers to be added and removed on the fly with no downtime! 

https://github.com/SteveLTN/https-portal

I have been really struggling for a couple weeks now to get nginx-proxy + letsencrypt to work with multiple containers (although that's most likely due to my lack of knowledge as much as anything else ;)

**Comment by jwilder** [comment]
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion resolves this.
