### ISSUE TITLE
Disable default host and return 444 for HTTP(S)

### ISSUE THREAD

**Issue by MathieuViossat** [jwilder/nginx-proxy#365]
How to disable the default host and return the code 444 (non-standard code that closes the connection). Currently, if DEFAULT_HOST is not provided, a random vhost is delivered.

I have added these lines in a config file:

```nginx
server {
    listen   80 default_server;
#    listen   443 default_server;
    return   444;
}
```

It works for non-HTTPS. Now if I uncomment the line for 443 (HTTPS), I get:
`no "ssl_certificate" is defined in server listening on SSL port while SSL handshaking, client: X.X.X.X, server: 0.0.0.0:443`

**Comment by ganehag** [comment]
If no default_server is defined then the default server is the first one, which is nginx’s standard default behaviour.

When a docker container with VIRTUAL_HOST is started or stopped. It generate a new config for nginx-proxy. If SSL support is configured and the crt & key files exists, a server block with port 443 will be added to the configuration file. The config file has this following statement at the top, and since this is the first server statement it will become the default_server if not default_server is defined.

```
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
```

This matches every host not defined in the config file but only for port 80 (HTTP). Accessing a VHOST on port 80 when the container is down results in a 503 error. But if the same VHOST is accessed on 443 (HTTPS) nginx has not been given any specific rules how to handle this.

In your example you are probably missing a bunch of ssl_* directives. The problem is that a "fallback" host should catch all non matching hosts. It is not obvious from a configuration standpoint which SSL certificate to use in this situation. But nginx-proxy can handle this scenario as well. At the very end of the config template it checks for the existence of a "default.crt" and "default.key" in the certs directory.

```
{{ if (and (exists "/etc/nginx/certs/default.crt") (exists "/etc/nginx/certs/default.key")) }}
server {
	server_name {{ $host }};
	listen 443 ssl http2 {{ $default_server }};
	access_log /var/log/nginx/access.log vhost;
	return 503;

	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
{{ end }}
```

This certificate needs to be a SNI cert with all of the domains handled by this nginx-proxy instance. 

This section will not forward any requests to a specific container. But it will report 503 error instead of replying with the content from another VIRTUAL_HOST when accessed over HTTPS.

If you want to force a single container to act as the default host. Then use DEFAULT_HOST=fallback.foo.bar.com. This single container could run any form of webserver you want. But for example it could run nginx plain docker container. With a configuration to return 444 error code on anything forced upon it.

Or you set up nginx-proxy in "Separate Containers" mode. Since this requires you to have the nginx.tmpl file on the host. So you are free to modify the **server_name "_"** section and change the 503 error code in it to 444 or whatever you want.

**Comment by MathieuViossat** [comment]
Thanks.
Your solution supposes to have a wildcard certificate, I don't. So, when someone try to access to `random.notfound.foo.example.com`, all browsers display a security warning because nginx provides the certificate of the first server who is listening 443.
Is there any option to return 444 (close connection) before sending a wrong certificate?

**Comment by ganehag** [comment]
I don't think that this is possible. When doing HTTPS the first thing is the SSL handshake. For this a valid or trusted certificate is required. This is sort of the whole point of HTTPS. To ensure the server is who is claims to be - before receiving further data.

```
$ nc google.com 80
GET /asdasd HTTP/1.0

HTTP/1.0 404 Not Found
Date: Thu, 18 Feb 2016 16:01:22 GMT
Content-Type: text/html
Server: HTTP server (unknown)
Content-Length: 49
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

<html><body><h1>404 Not Found</h1></body></html>
```

Any HTTP error is part of the HTTP protocol and should from the browsers perspective be ignored before ensuring the server is who it claims to be. Or to accept the security warning.

I know services which relies on semi random subdomains to handle communication. But this relies on wildcard certificates. This is the only solution for this. Or SNI with a LOT of domains.

> ec92c6fa499046ed9e537723ad8791a8.my-service.example.com

You can achieve what you want. But not with HTTPS only with HTTP.

**Comment by MathieuViossat** [comment]
I have finally created a self-signed wildcard certificate.
