### ISSUE TITLE
Can't open foo.bar.com

### ISSUE THREAD

**Issue by ganlanyuan** [jwilder/nginx-proxy#538]
Hey,
I ran the command
```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock -t jwilder/nginx-proxy
```
and then
```
docker run -e VIRTUAL_HOST=foo.bar.com,www.foo.bar.com -it --name web -v $(pwd):/usr/src/www/app web sh
```
In the Dockerfile `EXPOSE 80`.
But I can't open foo.bar.com in the browser, could you help me figure out what's wrong?

**Comment by wader** [comment]
What error do you get? what do you see in the nginx-proxy container log? request, config rebuilds events? You mean the Dockerfile used to build `web` image has `EXPOSE 80`? do you start a web  server in the shell your running?

**Comment by ganlanyuan** [comment]
There's no error or other information, it just shows "Server not found" when I try to open http://foo.bar.com/ in the browser.
I didn't run web server in the shell.

**Comment by wader** [comment]
Not "503 Service Temporarily Unavailable"? but it's a error page returned by nginx-proxy not a browser error page?
But is there any web server running in the `web` container?

**Comment by ganlanyuan** [comment]
Not "503 Service Temporarily Unavailable".
Some gulp tasks are running in the `web` container, but no server.

**Comment by wader** [comment]
Not sure i follow what you want to do. So there will be a server running in the web container? otherwise there is nothing responding to the proxied requests from nginx-proxy.
But it sounds like you can't even reach the nginx-proxy? what does foo.bar.com resolve to, is it actually the IP used by nginx-proxy?

**Comment by ganlanyuan** [comment]
Never mind, I gonna use php server instead.

**Comment by RafaelKr** [comment]
Maybe you can't reach foo.bar.com, because it doesn't resolve to your localhost.
If you're using Linux/OS X then type `sudo bash -c 'echo "127.0.0.1 foo.bar.com" >> /etc/hosts'` into your terminal. If you're using Windows, run notepad as Administrator and open the file `C:\Windows\System32\drivers\etc\hosts` and add the line `127.0.0.1 foo.bar.com`.

You also would have to do this with a php server. If you already did that, I'm sorry, then I also don't have any idea.

**Comment by ganlanyuan** [comment]
Thank you, @RafaelKr, 
I just want to set up a local server with docker. Will try to find other ways.
