### ISSUE TITLE
New tag version

### ISSUE THREAD

**Issue by gimler** [jwilder/nginx-proxy#559]
Please create a tag for the latest changes. The last 0.4 ist from May

**Comment by schmunk42** [comment]
A monthly release cycle would be nice.

**Comment by gimler** [comment]
ping

**Comment by schmunk42** [comment]
ping

**Comment by mjrussell** [comment]
This seems like a no brainer...not sure why it hasn't been done yet. Depending on latest isn't ideal since it could introduce breaking changes or unexpected bugs (I know tags can be moved around but unlikely you'd move a version tag)

In the mean time, I can use this mildly unpleasant workaround:

`docker pull jwilder/nginx-proxy@sha256:d5bbd7f242dd43490b5ebdab9b323fe2cb28a6ff76ee1f597f64832f6a7ca7c3`

**Comment by schmunk42** [comment]
@jwilder It would really be great if you could provide tags on a more regular basis. 🙇

**Comment by jwilder** [comment]
There's an 0.5.0 (since last nov) and I just tagged 0.6.0 and setup some build triggers to also create `alpine-0.6.0` tags automatically in the future.
