### ISSUE TITLE
How to load-balance dockerised servers without port conflicts

### ISSUE THREAD

**Issue by shongololo** [jwilder/nginx-proxy#638]
I have a dockerised server that listens for connections on 0.0.0.0:8080, and I would like to create multiple instances of this server and use nginx-proxy to load-balance requests to these instances.

My understanding is that load-balancing is possible with nginx-proxy by setting multiple containers to the same VIRTUAL_HOST environment variable.

What I fail to understand is how to map multiple containers to the same load-balanced VIRTUAL_HOST without running into port conflicts. If I map each container's internal port `8080` to a unique host port number, e.g. `8081`, `8082`, etc., then nginx-proxy returns a `service temporarily unavailable error` unless I specifically attach a container's mapped host port to the query.

i.e.
`my_virtual_host.com/api/path` does not work, whereas:
`my_virtual_host.com:8081/api/path` does work.

**Comment by wader** [comment]
Hi, you should not need to expose the containers on host ports for nginx-proxy to be able to connected to them. Maybe having a look at the generated config will give a clue what is going on. A common problem is that port heuristics in nginx-proxy selects to wrong port, try to force port with `VIRTUAL_PORT`.

The reason connecting to `:8081` works is because you then don't go thru nginx-proxy at all.

**Comment by shongololo** [comment]
Thanks, I wondered if that was the reason `:8081` worked. 

I tried without exposing the ports and with using the `VIRTUAL_PORT` but couldn't seem to get it figured out.
