### ISSUE TITLE
Proxy ssh connection with nginx

### ISSUE THREAD

**Issue by DRogue1337** [jwilder/nginx-proxy#823]
As of this SE answer: https://unix.stackexchange.com/a/293663/188985
it seems possible to proxy the ssh connection via nginx.

Then I could change `ssh://git@test.gitlab.code.ag:22000/root/test.git` to `ssh://git@test.gitlab.code.ag:root/test.git`, so that it's listening on port 22 and the `nginx-proxy` container is forwarding it.

Maybe someone with experience regarding `nginx tcp streaming` could look into it.

**Comment by gerrat** [comment]
I don't have any experience with this, but a comment on [this answer](https://stackoverflow.com/a/40135151/429982) seems to indicate this can't be done with SSH because "clients don't pass the DNS name".

**Comment by jwilder** [comment]
This is not supported in the way that nginx-proxy works to map virtual hosts to backend containers.  It works for HTTP(s) because clients sent a `Host` header which indicates what virtual host they are trying to reach.  For raw TCP, there isn't a `Host` header so there is no way to figure out what container should receive the request.  

You could certainly add in support for proxying all SSH connection to a specific container, but it wouldn't work the same way that the current `VIRTUAL_HOST` model works.  You could probably have nginx listen on separate ports or IPs and have all connection to that port go to a specific backend.

**Comment by jheusala** [comment]
It could be possible same way as already for SMTP, IMAP and POP3, using an authentication server: https://www.nginx.com/resources/admin-guide/mail-proxy/
