### ISSUE TITLE
Run nginx-proxy on a separate server instance

### ISSUE THREAD

**Issue by ltarasiewicz** [jwilder/nginx-proxy#868]
Hello,

Is it possible to run nginx proxy on a separate server instance from the one where other containers monitored by the proxy are started/stopped?

Or in other words, can nginx proxy talk to Docker API over the network and not the socket file (/var/run/docker.sock)?

**Comment by Pimmetje** [comment]
According to the docs i would think so:
```
  -endpoint string
      docker api endpoint (tcp|unix://..). Default unix:///var/run/docker.sock
```
https://github.com/jwilder/docker-gen#usage

**Comment by jwilder** [comment]
Yes, you would use the docker environment variables.  They currently default to `unix:///tmp/docker.sock` in the image. See https://github.com/jwilder/nginx-proxy/blob/master/Dockerfile#L30

```
Environment Variables:
  DOCKER_HOST - default value for -endpoint
  DOCKER_CERT_PATH - directory path containing key.pem, cert.pem and ca.pem
  DOCKER_TLS_VERIFY - enable client TLS verification
```

You'll have to mount in the cert dir so that the container can access that path if TLS is enabled on the remote docker endpoint.
