### ISSUE TITLE
Project still active ?

### ISSUE THREAD

**Issue by mroberty8** [jwilder/nginx-proxy#895]
Hi,

I would like to know if this current project is still active ?
I see a lot of waiting pull request, and no recent changes.

Thanks in advance.

**Comment by Ultimater** [comment]
I think you're aiming at "still active" not "already active" (I'm guessing English isn't your first language).
18 days ago PR 882 was merged, so I would say it's an active project. Jason's last github activity, including private repos, was a week ago. He's probably just been busy.

**Comment by riemers** [comment]
I have to agree with @mroberty8 though, i was looking into this project too. While it still works as advertised it seems not everything is taken into account. Of course one can be busy, but this is after all a community effort most of the time. He could assign more people to edit/merge request on his behalf sort of speak. In my case i wanted subdirs, which i found [**here**](https://github.com/theit8514/nginx-proxy-subdirectory) and found PR's or attempts at it in this repo too. Some issues date back to 2015? Active.. yes. But far from up to date. Hence my suggestion, reach out to some willing PR people and let them do some work too? And what is with the forks on this repo too? 1211 forks? Almost sounds like everybody started branching off for the things they needed (so i can't actually see if there is a newer more up to date version too)

**Comment by jwilder** [comment]
Yes, this project is still active.  I work on it when I can in my spare time.  I merge features which I consider to be worth the effort to maintain and provide the most benefit to people.  I also try to keep a level of stability since many people rely on the project.   A lot of feature requests are one-off things that people need for their specific use case.  These _may_ be useful to others, but I don't close them immediately since I don't know if they are useful for others yet.  This probably leads to PRs staying open for a long periods of time and lingering unfortunately.

I'm guessing the number of forks is high because the project is intended to be extended to support all the various features people need.  Forking the project and changing the template is probably how people are creating customizations.  There are other (better) ways to do it but, that's probably the simplest thing for most people.
