### ISSUE TITLE
passing in env options

### ISSUE THREAD

**Issue by jmls** [jwilder/nginx-proxy#93]
when you start nginx proxy with docker, you can use -e VIRTUAL_HOST=foo.bar.tz

I would like to use something similar (e.g for the location of a public folder) so, I tried to add

-e PUBLIC_FOLDER=foo

can I reference this using $container.Env.PUBLIC_FOLDER ? all my attempts come to naught :( I don't know if this is a bug or a problem with my understanding

If, I may be cheeky, this option isn't passed, can I default a variable to a value ?

something along the lines of set $pubDir = ($container.Env.PUBLIC_FOLDER) ? $container.Env.PUBLIC_FOLDER : "mypubDir"

nginx config is .. so .. confusing .. ;)

thanks

**Comment by jwilder** [comment]
Yes, you can access any env variable set on the container like you are trying.  It might be failing for you because $container might not be in scope where you are accessing it. 

https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L40

Groups each container by it's VIRTUAL_HOST env var so $host is the host is $containers is a list of containers with that $host.  $container is accessible in that scope after https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L43

You could try something like: https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L72

which grabs the first value for `CERT_NAME` of any of the grouped containers.
