### ISSUE TITLE
Deny traffic to hosts (Stop serving unkown hosts)

### ISSUE THREAD

**Issue by returntrip** [jwilder/nginx-proxy#950]
I am using nginx-proxy for 2 virtual hosts which I will call:

`nextcloud.server.com` and `ttrss.server.com`. 

They share the same public IP and all works perfectly fine.

I also have 2 more hosts that share the same public IP with the 2 above host (I use them as Dyndns for my openvpn). I will call them:

`router.server.com`  and `router.weirdname.com`

How can I configure `nginx-proxy` to deny traffic to ports 80 and 443 towards `router.server.com`  and `router.weirdname.com`? In practice, I do not want those 2 hosts to be accessible from browsers.

Thanks.

**Comment by kamermans** [comment]
If I understand you correctly, it sounds like you have the same problem as me, for which I have submitted a pull request: https://github.com/jwilder/nginx-proxy/pull/842

I'll demonstrate the features added by my PR with your example above.

First, start my branch of `nginx-proxy` with the update:
```
docker run -d -p 80:80 \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  kamermans/nginx-proxy:feature_external_internal_network
```

Next, start your containers for `nextcloud.server.com` and `ttrss.server.com` as usual.

Now, start your containers for `router.server.com` and `router.weirdname.com`, but include the environment variable `NETWORK_ACCESS=internal`.

Now traffic from the public internet to `router.server.com` and `router.weirdname.com` will be blocked - only clients on your local network (and the other containers) will be able to access them.

**Comment by returntrip** [comment]
I think the situation is quite similar, in my case I would need only `deny all` in `/etc/nginx/network_internal.conf` (no need to access http/https from anywhere) for `router.server.com` and `router.weirdname.com` hosts.

The problem in my case is: `router.server.com` and `router.weirdname.com` are not docker containers but dyndns host names for a router. So I guess I cannot declare `NETWORK_ACCESS=internal`.

I also use `docker-gen` + `nginx`, I think, your branch is based on `nginx-proxy` so I would need to understand how to adapt it to my case

Any hints how could I adapt your solution for my needs? I guess it is a matter of modifying the nginx.tmpl file and include create `/etc/nginx/network_internal.conf` with `deny all`

**Comment by kamermans** [comment]
I think I am still a bit confused, but it sounds like you're not using `nginx-proxy` at all.

In any case, the instance of `nginx` that answers requests on the server in question needs to block traffic to those two host names.  A `deny all` in the locations for those hosts would do the trick, but stock `nginx` will already serve an `HTTP 503` to clients that ask for a site that doesn't exist, so as far as I can tell, it should already be doing what you want.

That leads me to my next question: when you send a request to `router.server.com`, for example, what content do you get (the content from `nextcloud.server.com` or `ttrss.server.com` or something else?).

If there is a `location` in your `nginx` conf that answers requests for `router.server.com` and `router.weirdname.com`, why don't you just remove it?

**Comment by returntrip** [comment]
Thanks for helping Steven. 

I will start from your question:

if I visit `http://router.server.com` I get routed to redirected to `https://router.server.com`, get an  SSL error: NET::ERR_CERT_COMMON_NAME_INVALID and I am unable to access the hosts. The error is: "This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.". The same error  happens when I visit `https://router.weirdname.com`.

If I visit `http://router.weirdname.com` I get an error: "503 Service Temporarily Unavailable"

I use https://github.com/jwilder/docker-gen to generate the reverse proxy configuration for `nginx` container.

If I look at the generated `/etc/nginx/conf.d/default.conf` in the `nginx` container, I do not see any blocks for `router.server.com` or `router.weirdname.com` (which is right cause I have not declared them.

As you can see, I  am no nginx expert, but  I would have thought that the default behaviour of `nginx-proxy` or `docker-gen` would be to allow traffic only to hosts that are specifically declared, but it looks like this is not happening. Is this perhaps a bug in `docker-gen` or `nginx-proxy`?

**Comment by kamermans** [comment]
Thanks for the info - I'm happy to help!  It makes sense to me now.

First, the expected behavior is to get an `HTTP 503 Service Temporarily Unavailable` for sites that have no `location`.  In your case `router.weirdname.com` is working correctly.

When you attempt to visit `http://router.server.com`, your browser is checking something called its HTTP Strict Transport Security (HSTS) cache before it sends any requests.  In your case, at some point in past (possibly a long time ago), you sent a request to that domain and it answered with an HTTPS response including a header like `Strict-Transport-Security: max-age=31536000`.  **This header told your browser that it should never send any requests to this domain over HTTP**, and inserted that domain into its HSTS cache.  Now, any time you try to visit that domain with `http://`, your browser is redirecting you to the `https://` version - this happens without sending anything to the server since it's cached.  First you need to [clear the HSTS cache for `router.server.com`](https://andystechlife.wordpress.com/2016/09/18/how-to-clear-hsts-settings-in-chrome-and-firefox/) in your browser.

Once you clear HSTS you will not see the HTTPS/SSL errors, but I'll explain them too.

So, now your browser has autonomously decided to go to `https://router.server.com`.  That request hits NGINX, and NGINX wants to serve you an `HTTP 503 Service Temporarily Unavailable` like it's supposed to, but now you're on HTTPS, so it has no choice but to serve you an SSL certificate since even the error message has to be encrypted now.  Since there is no SSL certificate for that location, it grabs the first one it can find and uses it - hoping for the best (hence the `NET::ERR_CERT_COMMON_NAME_INVALID`.

Since your browser has remembered that this site wants to use Strict Transport Security, it refuses to show the content for the wrong SSL certificate (the `HTTP 503`), instead showing you an HSTS error.

**Comment by returntrip** [comment]
Great explanation.... Lesson learned on HSTS caching :)

I have downloaded Ffox Nightly (never used on a test machine), went to `http://router.server.com` and it is now showing error 503.... So good to until now...

When I browse `https://router.server.com` and  `https://router.weirdname.com` I get: `Error code: SSL_ERROR_BAD_CERT_DOMAIN`. I do not understand why?!?!

If I add an exception I see that the `nextcloud.server.com` SSL certificate is being diisplayed and I am redirected to a Nextcloud page saying: "You are accessing the server from an untrusted domain." (fair enough).....

I do not get why nginx is not denying, stopping the requests to https for those 2 domains that have no server  block and fishing the first available SSL cert (like you are saying). What can I do to stop this??? :)

**Comment by kamermans** [comment]
Thanks!

You can't stop it from answering the request - when you connect to port 443, you have to "speak HTTP" to the server before it can even decide that you shouldn't be able to connect.  If it doesn't answer your connection request, how can it know what domain you're trying to talk to?  Since it's already answered your request, then realized there is no appropriate `location` block, it has to decide what to do.  You can serve an error (like it's already doing), but you can't kill the connection completely (as far as I know) since it would generate a protocol error.

You're seeing the SSL cert from another domain, but you shouldn't be seeing the content from that site - if you are, there must be a `location` block with a `default_server` directive or something, instructing `nginx` to use that site to answer unmatched requests.

**Comment by returntrip** [comment]
If you have time, can you please look at my (docker-gen) generated nginx config and let me know if you spot anything that is causing the issue (erroneously fetching content from the nextcloud host). I cannot see a `default_server`location in it. I have only removed the ciphers to make the file shorter:
```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# nextcloud.server.com
upstream nextcloud.server.com {
				## Can be connect with "nginxle_proxy-tier" network
			# nextcloud_web_1
			server 172.22.0.9:80;
}
server {
	server_name nextcloud.server.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name nextcloud.server.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'removed to shorten';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/nextcloud.server.com.crt;
	ssl_certificate_key /etc/nginx/certs/nextcloud.server.com.key;
	ssl_dhparam /etc/nginx/certs/nextcloud.server.com.dhparam.pem;
	add_header Strict-Transport-Security "max-age=31536000";
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://nextcloud.server.com;
	}
}
# ttrss.server.com
upstream ttrss.server.com {
				## Can be connect with "nginxle_proxy-tier" network
			# tt-rss
			server 172.22.0.5:80;
}
server {
	server_name ttrss.server.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name ttrss.server.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'removed_to_shorten';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/ttrss.server.com.crt;
	ssl_certificate_key /etc/nginx/certs/ttrss.server.com.key;
	ssl_dhparam /etc/nginx/certs/ttrss.server.com.dhparam.pem;
	add_header Strict-Transport-Security "max-age=31536000";
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://ttrss.server.com;
	}
}
```

**Comment by kamermans** [comment]
Well, you've really got me curious now!  I recreated your scenario more-or-less exactly with a `docker-compose.yml`, a slightly modified `default.conf` and some self-signed certs: https://gist.github.com/kamermans/3b371f362265cf4332e8ae732ccff152

Results: you're exactly right!  I couldn't find any authoritative answer on why this happens, but I'd wager to bet that nginx has no choice but to try the first SSL certificate it can find since no other certs match the SNI host given.  Apparently you are then pushed into that `location` block and things continue as if you had sent that hostname!

Here's how you can fix it.  There's actually a "magic" response code in nginx called `444` that will basically kill the connection instead of returning content.  In your case, you want to kill connections to undefined hosts.

These blocks will do the trick in my tests:

```
# Default server for SSL to prevent leaking content from random vhost
server {
	listen 443 ssl http2 default_server;

	server_name _;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/ttrss.server.com.crt;
	ssl_certificate_key /etc/nginx/certs/ttrss.server.com.key;

	return      444;
}

# With this block you will kill HTTP connections instead of throwing 503s:
server {
	listen 80 default_server;
	server_name _;

	return      444;
}
```

**Comment by returntrip** [comment]
Thanks for sticking with me!

I have finally managed to make it work using:`docker-gen` container, official `nginx` container and the standard `nginx.tmlp`.

I have had to correct the path to `ssl_dhparam` from `/etc/nginx/dhparam/dhparam.pem` to `/etc/nginx/certs/dhparam.pem`, as per https://github.com/jwilder/nginx-proxy/issues/879

After that, I have manually generated `default.crt` and `default.key` in `/etc/nginx/certs/`

Now, when I reach `https://router.server.com` and `https://router.weirdname.com` I get a certificate warning, if I accept the cert I get error 503 instead of the content from `nextcloud.server.com`

**Comment by kamermans** [comment]
Very nice, thanks for sharing!

**Comment by returntrip** [comment]
@kamermans Could you please help me with a sanity check before I update https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/264?

Basically, i think, since this change to nginx.tmpl: https://github.com/jwilder/nginx-proxy/commit/02121df3b914061040df128e8266ccad81ce3046#diff-6c19a779564e1e2f88854a4a2fffbb78, which adds the default `dhparam.pem` in `/etc/nginx/dhparam/`, there is an issue with https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion, in the sense that:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/entrypoint.sh#L64
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/entrypoint.sh#L67
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/letsencrypt_service#L32

should be updated with the correct path to `dhparam.pem` from `/etc/nginx/certs/` to `/etc/nginx/dhparam/`

Or should it be the other way round : 

https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L45 should be update with the `dhparam.pem` path pointing to `/etc/nginx/certs/`?

If the path is not corrected (in the `nginx.tmpl`, in my case, because I have not tried modifying the companion letsencrypt app code), then `nginx` throws the following error (and its container keeps restarting):

```
2017/10/20 08:09:34 [emerg] 1#1: BIO_new_file("/etc/nginx/dhparam/dhparam.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/dhparam/dhparam.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2017/10/20 08:09:35 [emerg] 1#1: BIO_new_file("/etc/nginx/dhparam/dhparam.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/dhparam/dhparam.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
